import React, { useState, useEffect } from "react";
import { useSelector, useDispatch } from "react-redux";
import { fetchAssignedStudents } from "../features/advisor/advisorSlice";
import api from "../api/axios";
/**
 * AssignReviewModal - Modal for assigning a review to a student
 */
const AssignReviewModal = ({ isOpen, onClose, onSubmit, isLoading, preselectedReviewer = null }) => {
    const dispatch = useDispatch();
    const { students, reviewers } = useSelector((state) => state.advisor);

    const [formData, setFormData] = useState({
        studentId: "",
        reviewerId: preselectedReviewer?.id || "",
        date: "",
        slotId: "", // Selected slot ID
        time: "", // Will be derived from slot
        mode: "online",
        week: 1,
        meetingLink: "", // Required for online mode
        location: "", // Required for offline mode
    });
    const [error, setError] = useState("");
    const [availableSlots, setAvailableSlots] = useState([]);
    const [slotsLoading, setSlotsLoading] = useState(false);

    useEffect(() => {
        if (isOpen) {
            dispatch(fetchAssignedStudents());
            if (preselectedReviewer) {
                setFormData(prev => ({ ...prev, reviewerId: preselectedReviewer._id }));
            }
        }
        if (!isOpen) {
            setFormData({
                studentId: "",
                reviewerId: preselectedReviewer?._id || "",
                date: "",
                slotId: "",
                time: "",
                mode: "online",
                week: 1,
                meetingLink: "",
                location: "",
            });
            setError("");
            setAvailableSlots([]);
        }
    }, [isOpen, dispatch, preselectedReviewer]);

    // Fetch available slots when reviewer and date are selected
    useEffect(() => {
        if (!formData.reviewerId || !formData.date) {
            setAvailableSlots([]);
            return;
        }

        const fetchSlots = async () => {
            setSlotsLoading(true);
            try {
                const res = await api.get(`/reviewer/availability/by-date?date=${formData.date}&reviewerId=${formData.reviewerId}`);
                setAvailableSlots(res.data || []);
            } catch (err) {
                console.error("Failed to fetch slots:", err);
                setAvailableSlots([]);
            } finally {
                setSlotsLoading(false);
            }
        };
        fetchSlots();
    }, [formData.reviewerId, formData.date]);

    if (!isOpen) return null;

    const handleChange = (e) => {
        const { name, value } = e.target;

        // When slot is selected, also set the time
        if (name === "slotId") {
            const selectedSlot = availableSlots.find(s => s._id === value);
            setFormData(prev => ({
                ...prev,
                slotId: value,
                time: selectedSlot?.startTime || ""
            }));
        } else {
            // Reset slot when reviewer or date changes
            if (name === "reviewerId" || name === "date") {
                setFormData(prev => ({ ...prev, [name]: value, slotId: "", time: "" }));
            } else {
                setFormData(prev => ({ ...prev, [name]: value }));
            }
        }
    };

    const handleSubmit = (e) => {
        e.preventDefault();
        setError("");

        if (!formData.studentId || !formData.reviewerId || !formData.date || !formData.slotId) {
            setError("Please fill all required fields and select a time slot");
            return;
        }

        // Offline mode requires location
        if (formData.mode === "offline" && !formData.location.trim()) {
            setError("Location is required for offline reviews");
            return;
        }

        const scheduledAt = new Date(`${formData.date}T${formData.time}`);
        if (scheduledAt <= new Date()) {
            setError("Please select a future date and time");
            return;
        }

        // Note: meetingLink is auto-generated by backend for online mode
        onSubmit({
            studentId: formData.studentId,
            reviewerId: formData.reviewerId,
            scheduledAt: scheduledAt.toISOString(),
            mode: formData.mode,
            week: parseInt(formData.week),
            location: formData.mode === "offline" ? formData.location.trim() : null,
        });
    };

    return (
        <div className="fixed inset-0 z-50 flex items-center justify-center">
            {/* Backdrop */}
            <div
                className="absolute inset-0 bg-slate-900/40 backdrop-blur-sm"
                onClick={onClose}
            />

            {/* Modal */}
            <div className="relative bg-white rounded-xl shadow-2xl w-full max-w-lg mx-4">
                {/* Header */}
                <div className="flex items-center justify-between px-6 py-4 border-b border-slate-200">
                    <h3 className="text-lg font-semibold text-slate-900">Assign Review</h3>
                    <button
                        onClick={onClose}
                        disabled={isLoading}
                        className="text-slate-400 hover:text-slate-600 transition-colors disabled:opacity-50"
                    >
                        <svg className="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
                        </svg>
                    </button>
                </div>

                {/* Content */}
                <form onSubmit={handleSubmit} className="p-6 space-y-4">
                    {/* Error */}
                    {error && (
                        <div className="bg-red-50 border border-red-200 text-red-600 px-4 py-2 rounded-lg text-sm">
                            {error}
                        </div>
                    )}

                    {/* Student Select */}
                    <div>
                        <label className="block text-sm font-medium text-slate-700 mb-1.5">
                            Student <span className="text-red-500">*</span>
                        </label>
                        <select
                            name="studentId"
                            value={formData.studentId}
                            onChange={handleChange}
                            className="w-full px-4 py-2.5 border border-slate-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-green-500 focus:border-transparent"
                            disabled={isLoading}
                        >
                            <option value="">Select a student</option>
                            {students.map(student => (
                                <option key={student.id} value={student._id}>
                                    {student.name}
                                </option>
                            ))}
                        </select>
                    </div>

                    {/* Reviewer - Read Only (auto-assigned from selected card) */}
                    <div>
                        <label className="block text-sm font-medium text-slate-700 mb-1.5">
                            Reviewer
                        </label>
                        <div className="w-full px-4 py-2.5 border border-slate-200 rounded-lg bg-slate-50 text-slate-700">
                            {preselectedReviewer?.name || "No reviewer selected"}
                            {preselectedReviewer?.title && (
                                <span className="text-slate-500 ml-1">({preselectedReviewer.title})</span>
                            )}
                        </div>
                    </div>

                    {/* Week Number */}
                    <div>
                        <label className="block text-sm font-medium text-slate-700 mb-1.5">
                            Week Number
                        </label>
                        <input
                            type="number"
                            name="week"
                            value={formData.week}
                            onChange={handleChange}
                            min={1}
                            max={52}
                            className="w-full px-4 py-2.5 border border-slate-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-green-500 focus:border-transparent"
                            disabled={isLoading}
                        />
                    </div>

                    {/* Date & Time Slot */}
                    <div className="grid grid-cols-2 gap-4">
                        <div>
                            <label className="block text-sm font-medium text-slate-700 mb-1.5">
                                Date <span className="text-red-500">*</span>
                            </label>
                            <input
                                type="date"
                                name="date"
                                value={formData.date}
                                onChange={handleChange}
                                min={new Date().toISOString().split('T')[0]}
                                className="w-full px-4 py-2.5 border border-slate-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-green-500 focus:border-transparent"
                                disabled={isLoading}
                            />
                        </div>
                        <div>
                            <label className="block text-sm font-medium text-slate-700 mb-1.5">
                                Time Slot <span className="text-red-500">*</span>
                            </label>
                            {slotsLoading ? (
                                <div className="w-full px-4 py-2.5 border border-slate-300 rounded-lg bg-slate-50 text-slate-400 text-sm">
                                    Loading slots...
                                </div>
                            ) : !formData.reviewerId || !formData.date ? (
                                <div className="w-full px-4 py-2.5 border border-slate-200 rounded-lg bg-slate-50 text-slate-400 text-sm">
                                    Select date first
                                </div>
                            ) : availableSlots.length === 0 ? (
                                <div className="w-full px-4 py-2.5 border border-amber-200 rounded-lg bg-amber-50 text-amber-600 text-sm">
                                    No slots available
                                </div>
                            ) : (
                                <select
                                    name="slotId"
                                    value={formData.slotId}
                                    onChange={handleChange}
                                    className="w-full px-4 py-2.5 border border-slate-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-green-500 focus:border-transparent"
                                    disabled={isLoading}
                                >
                                    <option value="">Select time slot</option>
                                    {availableSlots.map(slot => {
                                        const formatTime = (time) => {
                                            if (!time) return "";
                                            const [h, m] = time.split(":");
                                            const hour = parseInt(h, 10);
                                            const ampm = hour >= 12 ? "PM" : "AM";
                                            return `${hour % 12 || 12}:${m} ${ampm}`;
                                        };
                                        return (
                                            <option
                                                key={slot._id}
                                                value={slot._id}
                                                disabled={slot.isBooked}
                                                style={slot.isBooked ? { color: '#dc2626' } : {}}
                                            >
                                                {formatTime(slot.startTime)} - {formatTime(slot.endTime)}
                                                {slot.isBooked ? ' (Not Available)' : ''}
                                            </option>
                                        );
                                    })}
                                </select>
                            )}
                        </div>
                    </div>

                    {/* Mode */}
                    <div>
                        <label className="block text-sm font-medium text-slate-700 mb-1.5">
                            Mode
                        </label>
                        <div className="flex gap-4">
                            <label className="flex items-center gap-2 cursor-pointer">
                                <input
                                    type="radio"
                                    name="mode"
                                    value="online"
                                    checked={formData.mode === "online"}
                                    onChange={handleChange}
                                    className="w-4 h-4 text-green-600 focus:ring-green-500"
                                    disabled={isLoading}
                                />
                                <span className="text-sm text-slate-700">Online</span>
                            </label>
                            <label className="flex items-center gap-2 cursor-pointer">
                                <input
                                    type="radio"
                                    name="mode"
                                    value="offline"
                                    checked={formData.mode === "offline"}
                                    onChange={handleChange}
                                    className="w-4 h-4 text-green-600 focus:ring-green-500"
                                    disabled={isLoading}
                                />
                                <span className="text-sm text-slate-700">Offline</span>
                            </label>
                        </div>
                    </div>

                    {/* Online Mode Info */}
                    {formData.mode === "online" && (
                        <div className="bg-blue-50 border border-blue-200 rounded-lg p-3">
                            <div className="flex items-start gap-2">
                                <svg className="w-5 h-5 text-blue-500 mt-0.5 flex-shrink-0" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15 10l4.553-2.276A1 1 0 0121 8.618v6.764a1 1 0 01-1.447.894L15 14M5 18h8a2 2 0 002-2V8a2 2 0 00-2-2H5a2 2 0 00-2 2v8a2 2 0 002 2z" />
                                </svg>
                                <div>
                                    <p className="text-sm font-medium text-blue-700">Video Call Meeting</p>
                                    <p className="text-xs text-blue-600 mt-0.5">
                                        A meeting link will be automatically generated and shared with participants.
                                    </p>
                                </div>
                            </div>
                        </div>
                    )}

                    {/* Location - for offline mode */}
                    {formData.mode === "offline" && (
                        <div>
                            <label className="block text-sm font-medium text-slate-700 mb-1.5">
                                Location <span className="text-red-500">*</span>
                            </label>
                            <input
                                type="text"
                                name="location"
                                value={formData.location}
                                onChange={handleChange}
                                placeholder="Room number, building, or address"
                                className="w-full px-4 py-2.5 border border-slate-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-green-500 focus:border-transparent"
                                disabled={isLoading}
                            />
                        </div>
                    )}

                    <div className="flex gap-3 pt-3">
                        <button
                            type="button"
                            onClick={onClose}
                            disabled={isLoading}
                            className="flex-1 py-2.5 bg-white border border-slate-300 text-slate-700 rounded-lg font-medium hover:bg-slate-50 transition-colors disabled:opacity-50"
                        >
                            Cancel
                        </button>
                        <button
                            type="submit"
                            disabled={isLoading}
                            className="flex-1 py-2.5 bg-green-600 text-white rounded-lg font-medium hover:bg-green-700 transition-colors disabled:opacity-50 flex items-center justify-center gap-2"
                        >
                            {isLoading ? (
                                <>
                                    <div className="w-4 h-4 border-2 border-white border-t-transparent rounded-full animate-spin"></div>
                                    Assigning...
                                </>
                            ) : (
                                "Assign Review"
                            )}
                        </button>
                    </div>
                </form>
            </div>
        </div>
    );
};

export default AssignReviewModal;
